<?php

namespace Eni\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* SectionTestRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class SectionTestRepository extends EntityRepository
{
}