<?php

namespace Eni\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* TestRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class ThemeRepository extends EntityRepository
{
	public function findByLibelle($libelle)
    {
		$alias = 't';
		$qb = $this->createQueryBuilder($alias);
		$qb
		->where('t.libelle LIKE :libelle')
		->setParameter('libelle', '%' . $libelle . '%')
		;

		return $qb->getQuery()->getOneOrNullResult();
	}
}