security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CANDIDAT:    ROLE_CANDIDAT
        ROLE_FORMATEUR:   ROLE_FORMATEUR

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider:       form.csrf_provider
                check_path:          fos_user_security_check
                login_path:          fos_user_security_login
                remember_me:         true
            remember_me:
                key: %secret%
                lifetime: 3600
                path: /
                domain: ~
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/, role: ROLE_FORMATEUR }
