<?php

namespace Eni\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
	public function findByUsername($username)
    {
        $alias = 'u';
        $qb = $this->createQueryBuilder($alias);
        $qb
            ->where('u.username LIKE :username')
            ->setParameter('username', '%' . $username . '%')
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
